//***********************************************************************
//***********************************************************************
//    ____  ____  _____  _______     ___      ______       __
//   |_   ||   _||_   _||_   __ \  .'   `.   / ____ `.    /  |
//     | |__| |    | |    | |__) |/  .-.  \  `'  __) |    `| |
//     |  __  |    | |    |  ___/ | |   | |  _  |__ '.     | |
//    _| |  | |_  _| |_  _| |_    \  `-'  / | \____) | _  _| |_
//   |____||____||_____||_____|    `.___.'   \______.'(_)|_____|
//
//=======================================================================
// Autogenerated code by HIPO 3.1 io library
// Modify the main loop to suite your needs
// Date: 07/17/2018
// Author: G.Gavalian
//***********************************************************************
#include <cstdlib>
#include <iostream>
#include "dictionary.h"
#include "bank.h"

int main(int argc, char** argv) {

    hipo::schema  sch("rec::event",30,1);
    sch.parse("pid/S,px/F,py/F,px/F,vx/F,vy/F,vz/F");
    sch.show();
    int item = 6;
    for(int i = 0 ;i < 6; i++){
      printf(" order = %4d, item = %4d, offset = %5d\n",
        i,item,sch.getOffset(item,i,6));

    }

    int size = sch.getSizeForRows(6);
    printf(" bank size = %d\n",size);

    hipo::bank dataBank(sch,12);
    dataBank.show();
}
//### END OF GENERATED CODE
