//***********************************************************************
//***********************************************************************
//    ____  ____  _____  _______     ___      ______       __
//   |_   ||   _||_   _||_   __ \  .'   `.   / ____ `.    /  |
//     | |__| |    | |    | |__) |/  .-.  \  `'  __) |    `| |
//     |  __  |    | |    |  ___/ | |   | |  _  |__ '.     | |
//    _| |  | |_  _| |_  _| |_    \  `-'  / | \____) | _  _| |_
//   |____||____||_____||_____|    `.___.'   \______.'(_)|_____|
//
//=======================================================================
// Autogenerated code by HIPO 3.1 io library
// Modify the main loop to suite your needs
// Date: 07/17/2018
// Author: G.Gavalian
//***********************************************************************
#include <cstdlib>
#include <iostream>
#include "reader.h"

extern "C" {
  void  hipo_file_open_( const char *filename, int length);
  int   hipo_file_next_(int* fstatus);
  void  hipo_read_bank_(const char *bankname, int *bankRows, int banknameLength);
  void  hipo_read_int_(const char *group, const char *item, int *nread, int *buffer, int *maxRows,
      int length_group, int length_item);
  void hipo_read_float_(const char *group, const char *item, int *nread, float *buffer, int *maxRows,
          int length_group, int length_item);
};

int main(int argc, char** argv) {

   std::cout << " reading file example program (HIPO) "  << __cplusplus << std::endl;

   char inputFile[256];
   char outputFile[256];

   if(argc>1) {
      sprintf(inputFile,"%s",argv[1]);
      //sprintf(outputFile,"%s",argv[2]);
   } else {
      std::cout << " *** please provide a file name..." << std::endl;
     exit(0);
   }

   int  status = 0;
   int counter = 0;
   int pbankid = 311;
   int bankRows;

   int pid[50];
   int maxPid = 50;
   int nread;

   float px[50];


   hipo_file_open_(inputFile,strlen(inputFile));

   while(status==0){
     hipo_file_next_(&status);
     hipo_read_bank_("REC::Particle",&bankRows,strlen("REC::Particle"));
     //printf(" number of rows = %5d\n",bankRows);
     hipo_read_int_("REC::Particle","pid",&nread,pid,&maxPid,
                strlen("REC::Particle"),strlen("pid"));

     for(int i = 0; i < nread; i++){
        //printf("%8d ", pid[i]);
     }
     //printf("\n");

     hipo_read_float_("REC::Particle","px",&nread,px,&maxPid,
                strlen("REC::Particle"),strlen("px"));
    for(int i = 0; i < nread; i++){
        //printf("%8.5f ", px[i]);
     }
     //printf("\n");
     counter++;
   }
   printf("processed # events %d\n",counter);
}
//### END OF GENERATED CODE
